config/routes.rb
Leaqweb::Application.routes.draw do

  get "parameter/suggest"

  devise_for :users

  resources :commodities do
    member do
      post :duplicate
    end
    collection do
      get :list
      delete :destroy_all
      get :suggest
      get :suggest_pollutant
      get :suggest_fuel
    end
  end

  resources :technologies do
    member do
      post :duplicate
      post :emission
    end
    collection do
      get :list
      delete :destroy_all
      get :suggest
    end
  end

  resources :demand_drivers do
    collection do
      get :list
      delete :destroy_all
    end
  end

  resources :demand_driver_values do
    collection do
      put :update_value
    end
  end

  resources :technology_sets do
    collection do
      get :list
      delete :destroy_all
      get :suggest
    end
  end

  resources :commodity_sets do
    collection do
      get :list
      delete :destroy_all
      get :suggest
    end
  end

  resources :combustions do
    collection do
      get :list
      get :import
      get :download
      post :zip
      post :upload
      delete :destroy_all
      put :update_value
    end
  end

  resources :solver_jobs do
    collection do
      get :list
      delete :destroy_all
    end
  end

  resources :parameter_values do
    collection do
      put :update_value
      post :destroy_all
      post :list
    end
  end

  resources :parameters do
    collection do
      get :suggest
    end
  end

  resources :result_sets do
     member do
       get :file
     end
     collection do
       post :import
       get :list
       get :suggest
       delete :destroy_all
     end
  end

  resources :scenarios do
     member do
       get :duplicate
     end
     collection do
       post :select
       get :list
       get :suggest
       delete :destroy_all
     end
  end

  resources :stored_queries do
     member do
       get :duplicate
     end
     collection do
       get :list
       get :import
       get :download
       post :upload
       post :zip
       delete :destroy_all
     end
  end

  resources :versions do
     collection do
       get :list
     end
  end

  resources :flows

  resources :energy_systems do
    member do
      get :backup
      get :restore
      post :upload
    end
    collection do
      post :select
    end
  end

  match '/check_db'          => 'dashboard#check_db', :as => 'check_db'
  match '/reset'             => 'dashboard#reset',    :as => 'reset_db'
  match 'query'              => 'query#index',        :as => 'query'
  get   'query_plot'         => 'query#result_plot',  :as => 'query_plot', :defaults => { :format => 'png' }
  post "versions/:id/revert" => "versions#revert",    :as => "revert_version"

  root :to => 'dashboard#index'

end

app/models/combustion.rb
#--
# Copyright (c) 2009-2012, Public Research Center Henri Tudor
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NON INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#++

require 'zip_tools'

class Combustion < ActiveRecord::Base

  #Interfaces
  has_paper_trail

  #Validations
  validates :value, presence: true, numericality: true

  #Scopes
  scope :matching_text, lambda { |text| where(['combustions.pollutant LIKE ? OR combustions.fuel LIKE ? OR combustions.source LIKE ?'] + ["%#{text}%"] * 3) }
  scope :matching_tag #empty because not taggable

  def self.import(filename)
    paper_trail_state  = PaperTrail.enabled?
    PaperTrail.enabled = false
    begin
      ZipTools::readline_zip(filename, Combustion) do |row|
        Combustion.create({fuel: row["fuel"],
                           pollutant: row["pollutant"],
                           value: row["value"],
                           source: row["source"]})
      end
    ensure
      PaperTrail.enabled = paper_trail_state
    end
  end

  def self.zip(filename, subset_ids=nil)
    Zip::ZipOutputStream.open(filename) do |zipfile|
      headers = %w{fuel pollutant value source}
      ZipTools::write_csv_into_zip(zipfile, Combustion, headers, subset_ids) do |pv, csv|
        csv << pv.attributes.values_at(*headers)
      end
    end
  end

end

app/controllers/combustions_controller.rb
#--
# Copyright (c) 2009-2012, Public Research Center Henri Tudor
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NON INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#++

class CombustionsController < ApplicationController

  before_filter :authenticate_user!

  respond_to :html, except: [:update_value,:list]
  respond_to :json, only:   [:update_value,:list]

  def index
    @combustion = Combustion.new
  end

  def list
    combustions = Combustion
    @combustions, @total_combustions = filter_list(combustions,%w(fuel pollutant value source))
    render layout: false, :formats => [:json], partial: "list"
  end

  def create
    case params[:do]
      when "add_pv"
        @combustion = Combustion.new(params[:combustion])
        if @combustion.save
          flash[:notice]='Combustion coefficient was successfully added.'
        else
          render action: "index"
          return
        end
      when "delete_pv"
        Combustion.where(id: checkbox_ids).map(&:destroy)
        flash[:notice]='Combustion coefficients have been deleted.'
    end
    redirect_to(combustions_path)
  end

  def update_value
    f = params[:field].split("-")
    value = Combustion.update(f.first.to_i, f.last=>params[:value]) ? params[:value] : ""
    render :json => value
  end

  def upload
    if params[:import] && File.exist?(params[:import]["combustion"].tempfile.path)
      Combustion.import(params[:import]["combustion"].tempfile.path)
      redirect_to(combustions_url, notice: 'File has been imported.')
    else
      redirect_to(combustions_url, notice: 'No file to upload.')
    end
  end

  def zip
    f = Tempfile.new("combustions")
    Combustion.zip(f.path,params[:combustions_id])
    send_file f.path, type: "application/zip",
                      filename: "combustions.zip"
  end

end

app/views/combustions/_list.json.erb
{
    "sEcho":<%= params[:sEcho].to_json.html_safe || -1.to_json.html_safe %>,
    "iTotalRecords":<%= Combustion.count.to_json.html_safe %>,
    "iTotalDisplayRecords":<%= @total_combustions.to_json.html_safe %>,
    "aaData":<%= @combustions.collect do |c|
                   [ check_box_tag("cb#{c.id}"),
                     "<span id='#{c.id}-fuel' class='edit'>#{c.fuel}</span>",
                     "<span id='#{c.id}-pollutant' class='edit'>#{c.pollutant}</span>",
                     "<span id='#{c.id}-value' class='edit'>#{c.value}</span>",
                     "<span id='#{c.id}-source' class='edit'>#{c.source}</span>",
                     ""]
                 end.to_json.html_safe %>
}

app/views/combustions/download.haml
.grid_2
  .box
    %h2 Action
    .block
      %p
        = link_to 'Browse...', combustions_path, :class => "action browse"
.grid_10
  .box
    %h2 Download a zipped file containing the combustion coefficients
    .block
      = form_tag(zip_combustions_path, :multipart => true) do
        %p= submit_tag "Download", :class => "button"
.clear

app/views/combustions/import.haml
.grid_2
  .box
    %h2 Action
    .block
      %p
        = link_to 'Browse...', combustions_path, :class => "action browse"
.grid_10
  .box
    %h2 Import combustion coefficients from a zipped file
    .block
      = form_tag(upload_combustions_path, :multipart => true) do
        = submit_tag "Upload", :disable_with => "Please wait...", :class => "button restore_db"
        = file_field 'import', 'combustion', :class => "db_file"
.clear

app/views/combustions/index.haml
:javascript
  function draw_editable() {
    $('.edit').editable(#{raw update_value_combustions_path.to_json},{
        style   : 'inherit',
        width   : "100%",
        height  : 18,
        method  : "PUT",
        id      : 'field',
        submitdata: {
          authenticity_token: #{raw form_authenticity_token.to_json}
        }
    });
  }
  $(document).ready(function() {
  	$('.list_table').dataTable( {
  		"bProcessing"    : true,
  		"bServerSide"    : true,
  	    "bFilter"        : true,
        "bLengthChange"  : true,
        "bStateSave"     : true,
        "bSort"          : true,
        "bInfo"          : true,
        "aaSorting"      : [[1,'asc']],
        "sPaginationType": "full_numbers",
        "iDisplayLength" : 25,
        "bAutoWidth"     : false,
  		"sAjaxSource"    : #{list_combustions_path.to_json},
  	    "fnServerData"   : function ( sSource, aoData, fnCallback ) {
            aoData.push( { "name": "set", "value": #{params[:set].to_json} } );
            $.getJSON( sSource, aoData, function (json) {
              fnCallback(json)
            } );
          },
        "fnDrawCallback": function() { draw_editable(); },
        "aoColumnDefs"   : [ {"bSortable" : false, "aTargets": [0,-1] }],
  	    "oLanguage"      : {"sSearch": "Filter:","sProcessing": #{image_tag("spinner.gif").to_json}},
  	    "sDom"           : 'lrftpi'
  	} );
    $( ".suggest_pollutant" ).autocomplete({
       source: #{suggest_pollutant_commodities_path.to_json},
       minLength: 2
     });
    $( ".suggest_fuel" ).autocomplete({
      source: #{suggest_fuel_commodities_path.to_json},
      minLength: 2
    });
  } );

.grid_2
  .box
    %h2 Action
    .block
      %p
        =link_to('Import...', import_combustions_path, :class => 'action import')
        =link_to('Download all...', download_combustions_path, :class => 'action backup_db')


.grid_10
  .box
    %h2 Combustion coefficients
    %p
      = form_tag(combustions_path,:method => "post",:id=>"form_") do
        %input(type="hidden" id="do" name="do" value="")
        %table(class="list_table" summary="Commodity list")
          %thead
            %th(class='check')
              = check_box_tag("click_check",nil,nil,:class=>"check_all")
            %th(class='name') Fuel
            %th(class='name') Pollutant
            %th(class='value') Value
            %th Source
            %th(class="check")
          %tbody
            %tr
              %td(colspan="6" class="list_table_empty")
                Loading data
          %tfoot
            %tr
              %th(class="check")
                = link_to "Delete", "#", :class => "action delete_pv", :confirm => "Are you sure?"
              %th(class='inputs')
                %input(type="textcell" class="suggest_fuel" id="new_fuel" name="combustion[fuel]")
              %th(class='inputs')
                %input(type="textcell" class="suggest_pollutant" id="new_pollutant" name="combustion[pollutant]")
              %th
                %input(type="textcell" id="combustion_value" name="combustion[value]")
              %th
                %input(type="textcell" id="combustion_source" name="combustion[source]")
              %th(class="check")
                = link_to_function "Add", "add_combustion()", :class => "action add_pv"

    %br
    %br