config/routes.rb
Leaqweb::Application.routes.draw do

  get "parameter/suggest"

  devise_for :users

  resources :commodities do
    member do
      post :duplicate
    end
    collection do
      get :list
      delete :destroy_all
      get :suggest
      get :suggest_pollutant
      get :suggest_fuel
    end
  end

  resources :technologies do
    member do
      post :duplicate
      post :emission
    end
    collection do
      get :list
      delete :destroy_all
      get :suggest
    end
  end

  resources :demand_drivers do
    collection do
      get :list
      delete :destroy_all
    end
  end

  resources :demand_driver_values do
    collection do
      put :update_value
    end
  end

  resources :technology_sets do
    collection do
      get :list
      delete :destroy_all
      get :suggest
    end
  end

  resources :commodity_sets do
    collection do
      get :list
      delete :destroy_all
      get :suggest
    end
  end

  resources :combustions do
    collection do
      get :list
      get :import
      get :download
      post :zip
      post :upload
      delete :destroy_all
      put :update_value
    end
  end

  resources :solver_jobs do
    collection do
      get :list
      delete :destroy_all
    end
  end

  resources :parameter_values do
    collection do
      put :update_value
      post :destroy_all
      post :list
    end
  end

  resources :parameters do
    collection do
      get :suggest
    end
  end

  resources :result_sets do
     member do
       get :file
     end
     collection do
       post :import
       get :list
       get :suggest
       delete :destroy_all
     end
  end

  resources :scenarios do
     member do
       get :duplicate
     end
     collection do
       post :select
       get :list
       get :suggest
       delete :destroy_all
     end
  end

  resources :stored_queries do
     member do
       get :duplicate
     end
     collection do
       get :list
       get :import
       get :download
       post :upload
       post :zip
       delete :destroy_all
     end
  end

  resources :versions do
     collection do
       get :list
     end
  end

  resources :flows

  resources :energy_systems do
    member do
      get :backup
      get :restore
      post :upload
    end
    collection do
      post :select
    end
  end

  match '/check_db'          => 'dashboard#check_db', :as => 'check_db'
  match '/reset'             => 'dashboard#reset',    :as => 'reset_db'
  match 'query'              => 'query#index',        :as => 'query'
  get   'query_plot'         => 'query#result_plot',  :as => 'query_plot', :defaults => { :format => 'png' }
  post "versions/:id/revert" => "versions#revert",    :as => "revert_version"

  root :to => 'dashboard#index'

end

app/models/commodity_set.rb
#--
# Copyright (c) 2009-2012, Public Research Center Henri Tudor
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NON INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#++

class CommoditySet < ActiveRecord::Base

  #Interfaces
  has_paper_trail
  acts_as_taggable_on :sets

  #Relations
  belongs_to :energy_system
  has_and_belongs_to_many :commodities
  has_many :parameter_values, dependent: :delete_all

  #Validations
  validates :energy_system, presence: true
  validates :name, presence: true,
                   uniqueness: true,
                   format: {with: /\A[a-zA-Z\d-]+\z/, message: "Please use only letters, numbers or '-' in name"}

  #Scopes
  scope :activated, tagged_with("AGG")
  scope :matching_text, lambda {|text| where(['name LIKE ? OR description LIKE ?'] + ["%#{text}%"] * 2) }
  scope :matching_tag, lambda {|tag| tagged_with(tag) if (tag && tag!="" && tag != "null")}

  def values_for(parameters, scenario_id)
    parameter_values.of(Array(parameters)).where(scenario_id: scenario_id).order(:year)
  end

end

app/controllers/commodity_sets_controller.rb
#--
# Copyright (c) 2009-2012, Public Research Center Henri Tudor
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NON INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#++

class CommoditySetsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :check_res!

  respond_to :html
  respond_to :json, only: [:show, :suggest]

  def index
  end

  def list
    @commodity_sets, @total_commodity_sets  = filter_list(commodity_sets,%w(name description))
    render layout: false, :formats => [:json], partial: "list"
  end

  def show
    @commodity_set = CommoditySet.find(params[:id])
    respond_to do |format|
      format.html { redirect_to edit_commodity_set_path(@commodity_set) }
      format.js { render json: {commodity_set: {id: @commodity_set.id, commodities: @commodity_set.commodities}}.to_json }
    end
  end

  def new
    respond_with(@commodity_set = CommoditySet.new)
  end

  def edit
    respond_with(@commodity_set = CommoditySet.find(params[:id]))
  end

  def create
    respond_with(@commodity_set = CommoditySet.create(params[:commodity_set]))
  end

  def update
    @commodity_set = CommoditySet.find(params[:id])
    case params[:do]
      when "update_commodities"
        @commodity_set.commodities = Commodity.find_by_list_name(params[:commodities])
        flash[:notice] = 'Commodity set was successfully created.' if @commodity_set.save
      when "update"
        @commodity_set.update_attributes(params[:commodity_set])
        respond_with(@commodity_set)
        return
      when "delete_pv"
        ParameterValue.where(id: checkbox_ids).map(&:destroy)
      when "add_pv"
        att = params[:pv]
        att[:parameter] = Parameter.find_by_name(att[:parameter])
        att[:commodity] = Commodity.find_by_name(att[:commodity]) if att[:commodity]
        att[:commodity_set] = @commodity_set
        pv = ParameterValue.new(att)
        flash[:notice] = 'Parameter value was successfully added.' if pv.save
    end if params[:do]
    redirect_to(edit_commodity_set_path(@commodity_set))
  end

  def destroy
    CommoditySet.find(params[:id]).destroy
    redirect_to(commodity_sets_url)
  end

  def destroy_all
    CommoditySet.where(:id=>checkbox_ids).map(&:destroy)
    redirect_to(commodity_sets_url)
  end

  def suggest
    text = params[:term]
    res = CommoditySet.order(:name).matching_text(text).limit(10).map(&:name)
    res << "..." if res.size==10
    render json: res.to_json
  end

  private

  def commodity_sets
    CommoditySet.where(:energy_system_id=>@current_res)
  end

end

app/views/commodity_sets/_list.json.erb
{
    "sEcho":<%= params[:sEcho].to_json.html_safe || -1.to_json.html_safe %>,
    "iTotalRecords":<%= CommoditySet.count.to_json.html_safe %>,
    "iTotalDisplayRecords":<%= @total_commodity_sets.to_json.html_safe %>,
    "aaData":<%= @commodity_sets.collect do |c|
                   [ check_box_tag("cb#{c.id}"),
                     link_to(c.name, edit_commodity_set_path(c)),
                     truncate(c.description, :omission => "...", :length => 100)]
                 end.to_json.html_safe %>
}

app/views/commodity_sets/edit.haml
:javascript
  $(document).ready(function() {
    $('#filter_commodity').keyup(function () {
      fill_avail_commodities('#{commodities_path}',$('#filter_commodity').val());
    });
    fill_avail_commodities('#{commodities_path}',$('#filter_commodity').val());
    fill_commodity_set('#{commodity_set_path(@commodity_set)}');
    $('#apply').click(function() {
        var com = $('#commodity_list option');
        var s = "";
        for(var i = 0; i < com.length; i++) {
            s += com[i].text + ",";
        }
        $.ajax({
            url:#{commodity_set_path(@commodity_set).to_json},
            type:'PUT',
            data:{
                'commodities':s.substring(0,s.length-1),
                'do':'update_commodities'
            },
            async:false
        });
        location.reload();
    });
  });

.grid_3
  .box(class="action")
    %h2 Actions
    %br
    %p
      = link_to 'Browse all', commodity_sets_path, :class => "action browse"
      = link_to 'New CommoditySet', new_commodity_set_path, :class => "action new"
    %p
      = link_to 'Delete', @commodity_set, :confirm => 'Are you sure?', :method => :delete, :class => "action delete"

  .box
    %h2 CommoditySet
    .block(id="idcard")
      = render :partial => 'shared/id_card', :locals => {:object => @commodity_set , :categories => nil}

.grid_9
  .box
    %h2 Commodities
    .block
    %p
      %table
        %thead
          %tr
            %th
              Available commodities
              %input(id="filter_commodity")
            %th#nb_commodity Commodity selected
        %tbody
          %tr
            %td.col50
              %select(multiple="multiple" size="10" id="avail_commodity" class="flow_list")
              %p(style="text-align: center")
                %a(href="#" id="add_commodity")
                  & add >>
            %td.col50
              %select(multiple="multiple" size="10" id="commodity_list" class="flow_list")
              %p(style="text-align: center")
                %a(href="#" id="remove_commodity")
                  & << remove
      = link_to 'Apply', '', :id => "apply", :class => "action"
      = link_to 'Reset Changes', commodity_set_path(@commodity_set), :class => "action"

  .box
    %h2 Parameters
    .block
      :erb
        <%= render :partial => 'shared/parameter_table',
                  :locals => { :object => @commodity_set,
                               :pid => "param",
                               :length_change => "false",
                               :filter => "false",
                               :request_path => commodity_set_path(@commodity_set),
                               :parameters => %w{agg_coef commodity_set_annual_up degree_of_use},
                               :cols => %w{parameter commodity year value source},
                               :editable => %w{value source},
                               :rules => {"=agg_coef" => %w{year}, "=commodity_set_annual_up" => %w{commodity} } }%>
.clear

app/views/commodity_sets/index.haml
:javascript
  $(document).ready(function() {
  	$('#list_table').dataTable( {
  		"bProcessing"    : true,
  		"bServerSide"    : true,
  	    "bFilter"        : true,
        "bLengthChange"  : true,
        "bStateSave"     : true,
        "bSort"          : true,
        "bInfo"          : true,
        "aaSorting"      : [[1,'asc']],
        "sPaginationType": "full_numbers",
        "iDisplayLength" : 25,
        "bAutoWidth"     : false,
  		"sAjaxSource"    : #{list_commodity_sets_path.to_json},
  	    "fnServerData"   : function ( sSource, aoData, fnCallback ) {
            aoData.push( { "name": "set", "value": #{params[:set].to_json} } );
            $.getJSON( sSource, aoData, function (json) {
              fnCallback(json)
            } );
          },
        "aoColumnDefs"   : [ {"bSortable" : false,   "aTargets": [0] } ],
  	    "oLanguage"      : {"sSearch": "Filter:","sProcessing": #{image_tag("spinner.gif").to_json}},
  	    "sDom"           : 'lrft<"dataTable_delete">pi'
  	} );
    $("div.dataTable_delete").html(#{submit_tag('Delete',:class=>'button delete',:confirm => "Are you sure?" ).to_json});
  } );
.grid_2
  .box(class="action")
    %h2 Actions
    %br
    %p
      = link_to 'New Commodity set', new_commodity_set_path, :class => "action new"

.grid_10
  .box
    %h2 Browse commodity sets
    %p
    = form_tag(destroy_all_commodity_sets_path,:method => "delete") do
      %table(id="list_table" summary="Commodity set list")
        %thead
          %th(class='check')
            = check_box_tag("click_check",nil,nil,:class=>"check_all")
          %th(class='name') Name
          %th Description
        %tbody
          %tr
            %td(colspan="3" class="list_table_empty")
              Loading data
    %br
    %br
    %br
.clear

app/views/commodity_sets/new.haml
.grid_2
  %div(class="box action")
    %h2 Actions
    %br
    %p= link_to 'Browse all', commodity_sets_path, :class => "action browse"

.grid_10
  .box
    %h2 New CommoditySet
    .block
      =simple_form_for @commodity_set do |f|
        =f.input :name
        =f.input :description, :input_html => {:rows => 2}
        =f.input :set_list, :as => :hidden, :input_html => {:value => "AGG"}
        =f.button :submit, :class => "aligned"
        = f.hidden_field :energy_system_id, value: @current_res.id
.clear