config/routes.rb
Leaqweb::Application.routes.draw do

  get "parameter/suggest"

  devise_for :users

  resources :commodities do
    member do
      post :duplicate
    end
    collection do
      get :list
      delete :destroy_all
      get :suggest
      get :suggest_pollutant
      get :suggest_fuel
    end
  end

  resources :technologies do
    member do
      post :duplicate
      post :emission
    end
    collection do
      get :list
      delete :destroy_all
      get :suggest
    end
  end

  resources :demand_drivers do
    collection do
      get :list
      delete :destroy_all
    end
  end

  resources :demand_driver_values do
    collection do
      put :update_value
    end
  end

  resources :technology_sets do
    collection do
      get :list
      delete :destroy_all
      get :suggest
    end
  end

  resources :commodity_sets do
    collection do
      get :list
      delete :destroy_all
      get :suggest
    end
  end

  resources :combustions do
    collection do
      get :list
      get :import
      get :download
      post :zip
      post :upload
      delete :destroy_all
      put :update_value
    end
  end

  resources :solver_jobs do
    collection do
      get :list
      delete :destroy_all
    end
  end

  resources :parameter_values do
    collection do
      put :update_value
      post :destroy_all
      post :list
    end
  end

  resources :parameters do
    collection do
      get :suggest
    end
  end

  resources :result_sets do
     member do
       get :file
     end
     collection do
       post :import
       get :list
       get :suggest
       delete :destroy_all
     end
  end

  resources :scenarios do
     member do
       get :duplicate
     end
     collection do
       post :select
       get :list
       get :suggest
       delete :destroy_all
     end
  end

  resources :stored_queries do
     member do
       get :duplicate
     end
     collection do
       get :list
       get :import
       get :download
       post :upload
       post :zip
       delete :destroy_all
     end
  end

  resources :versions do
     collection do
       get :list
     end
  end

  resources :flows

  resources :energy_systems do
    member do
      get :backup
      get :restore
      post :upload
    end
    collection do
      post :select
    end
  end

  match '/check_db'          => 'dashboard#check_db', :as => 'check_db'
  match '/reset'             => 'dashboard#reset',    :as => 'reset_db'
  match 'query'              => 'query#index',        :as => 'query'
  get   'query_plot'         => 'query#result_plot',  :as => 'query_plot', :defaults => { :format => 'png' }
  post "versions/:id/revert" => "versions#revert",    :as => "revert_version"

  root :to => 'dashboard#index'

end

app/models/technology.rb
#--
# Copyright (c) 2009-2012, Public Research Center Henri Tudor
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NON INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#++

require 'etem'

class Technology < ActiveRecord::Base
  include Etem

  #Interfaces
  has_paper_trail
  acts_as_taggable_on :sets

  #Relations
  belongs_to :energy_system
  has_many :out_flows, dependent: :destroy
  has_many :in_flows,  dependent: :destroy
  has_many :flows,     dependent: :destroy
  has_many :parameter_values, dependent: :delete_all
  has_and_belongs_to_many :technology_sets

  #Validations
  validates :energy_system, presence: true
  validates :name, presence: true,
                   uniqueness:  {scope: :energy_system_id},
                   format: {with: /\A[a-zA-Z\d-]+\z/, message: "Please use only letters, numbers or '-' in name"}

  # Categories [name,value]
  # sets in value has to be sorted by alphabetical order!!
  CATEGORIES = [
      ["Disabled", ""],
      ["Conversion Technology", "P"],
      ["Fuel Technology", "FUELTECH,P"],
      ["Demand device", "DMD,P"]
  ]

  #Scopes
  scope :activated, tagged_with("P")
  scope :matching_text, lambda {|text| where(['name LIKE ? OR description LIKE ?'] + ["%#{text}%"] * 2) }
  scope :matching_tag, lambda {|tag| tagged_with(tag) if (tag && tag!="" && tag != "null")}
  scope :find_by_list_name, lambda {|list| where(name: list.split(","))}

  def flow_act
    ParameterValue.of("flow_act").technology(self).first.flow
  end

  def flow_act=(flow)
    p = Parameter.find_by_name("flow_act")
    pv = parameter_values.where(parameter_id: p.id).first
    if pv
      ParameterValue.update(pv.id, flow: flow)
    else
      ParameterValue.create(energy_system: energy_system,
                            parameter:     p,
                            technology:    self,
                            flow:          flow,
                            value:         0,
                            scenario:      energy_system.base_scenario)
    end
  end

  def commodities
    collect_commodities(flows)
  end

  def outputs
    collect_commodities(out_flows)
  end

  def inputs
    collect_commodities(in_flows)
  end

  def collect_commodities(flows)
    Commodity.joins(:flows).where("flows.id"=>flows.map(&:id))
  end

  def values_for(parameters,scenario_id)
    parameter_values.of(Array(parameters)).where(scenario_id: scenario_id).order(:year)
  end

  def to_s
    self.name
  end

  # Duplicate the technology
  def duplicate(new_name=nil)
    new_name = next_available_name(Technology, self.name) unless new_name
    t = Technology.create(name:          new_name,
                          description:   self.description,
                          set_list:      self.set_list.join(','),
                          energy_system: energy_system)
    flow_hash = {}
    self.in_flows.each { |f|
      ff = InFlow.create
      flow_hash[f.id] = ff.id
      f.commodities.each { |c| ff.commodities << c }
      t.flows << ff
    }
    self.out_flows.each { |f|
      ff = OutFlow.create
      flow_hash[f.id] = ff.id
      f.commodities.each { |c| ff.commodities << c }
      t.flows << ff
    }
    parameters = signature.keys.select{|k| signature[k] &&
            (signature[k].include?("technology")||signature[k].include?("flow")||signature[k].include?("in_flow"))} +
            %w(input output)
    Scenario.all.each do |scen|
      values_for(parameters,scen.id).each do |pv|
        attributes = pv.attributes
        %w{flow_id in_flow_id out_flow_id}.each do |att|
          attributes[att] = flow_hash[attributes[att]]
        end
        attributes.delete("technology_id")
        t.parameter_values << ParameterValue.create(attributes)
      end
    end
    t.save
    t
  end

  # Read input/output parameters to create/update eff_flo / flo_shr_fx parameters
  def preprocess_input_output(scenario_id)

    #Read all input/output parameters
    io = %w(input output).collect { |p| values_for(p,scenario_id) }
    return if (io[0].size*io[1].size)==0

    #Classify inflow-outflow
    p = Hash.new
    io.each_index do |i|
      io[i].each do |r|
        key = "#{r.in_flow_id}-#{r.out_flow_id}"
        p[key] = {} unless p[key]
        p[key][i] = Hash.new(0) unless p[key][i]
        p[key][i][r.commodity_id] = r.value
      end
    end

    #create/update eff_flo
    p.each do |key, value|
      # check if input and outputs both exists
      if value.keys == [0, 1]

        kk = key.split("-")

        #eff-flo
        tot = value[0].values.sum
        efficiency = [value[1].values.sum/tot,0].max
        pv = ParameterValue.of("eff_flo").where("in_flow_id=? AND out_flow_id=?", kk[0], kk[1]).first
        if pv
          ParameterValue.update(pv.id, value: efficiency, source: "Preprocessed")
        else
          param = Parameter.find_by_name("eff_flo")
          ParameterValue.create(parameter_id: param.id,
                                technology_id: self.id,
                                in_flow_id: kk[0],
                                out_flow_id: kk[1],
                                value: efficiency,
                                scenario_id: scenario_id,
                                energy_system: energy_system,
                                source: "Preprocessed")
        end

        #flo_share_fx
        [0, 1].each do |x|
          param = Parameter.find_by_name("flo_share_fx")
          c = Flow.find(kk[x]).commodities
          if c.size > 1
            ParameterValue.destroy_all(parameter_id: param.id, flow_id: kk[x])
            total = value[x].values.sum
            #ensure sum is equal to 1
            coef = {}
            c.each { |j| coef[j.id] = [0,(value[x][j.id]/total*10**10).round(0).to_f/10**10].max }
            # Erreur arrondi
            if coef.values.sum > 1
              diff = coef.values.sum - 1
              selected_k = coef.select{|k,v| v>diff}.first.first
              coef[selected_k] -= diff
            end
            #set coefficients
            c.each do |j|
              pv = ParameterValue.create(parameter_id: param.id,
                                         technology_id: self.id,
                                         flow_id: kk[x],
                                         commodity_id: j.id,
                                         value: coef[j.id],
                                         scenario_id: scenario_id,
                                         energy_system: energy_system,
                                         source: "Preprocessed")
              pv
            end
          end
        end

      end
    end
  end

  # Compute eff_flo between two flows when out_flow is a pollutant
  def combustion_factor(in_flow, out_flow)
    in_flow = self.in_flows.first unless in_flow
    fuels = in_flow.commodities
    pollutant = out_flow.commodities.first
    coefs = Hash.new(0)
    Combustion.where(pollutant: pollutant.name).each { |c| coefs[c.fuel] = c.value }
    if fuels.size == 1
      coefs[fuels.first.name]
    else
      share = self.values_for("flo_share_fx",energy_system.base_scenario.id).where(flow_id: in_flow)
      share.collect! { |s| coefs[s.commodity.name] * s.value }
      share.inject(0) { |sum, x| sum+x }
    end
  end

  #return the corresponding set list from the CATEGORIES array
  def matching_set_list
    my_set = self.set_list.sort.join(",")
    s = nil
    CATEGORIES.each do |c|
      if c[1]==my_set
        s = c[1]
        break
      end
    end
    s
  end

end

app/controllers/technologies_controller.rb
#--
# Copyright (c) 2009-2012, Public Research Center Henri Tudor
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NON INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#++

class TechnologiesController < ApplicationController

  before_filter :authenticate_user!
  before_filter :check_res!

  respond_to :html, except: :list
  respond_to :json, only:   [:list, :index, :suggest]

  def index
    respond_to do |format|
      format.html { @last_visited = technologies.where(id: last_visited(Technology)) }
      format.js do
        t = technologies.order(:name).where(["name like ?","%#{params[:filter]}%"])
        render json: {"tech"  => t.map(&:name)}.to_json
      end
    end
  end

  def list
    @technologies, @total_technologies  = filter_list(technologies,%w(name description))
    render layout: false, :formats => [:json], partial: "list"
  end

  def show
    redirect_to edit_technology_path(technologies.find(params[:id]))
  end

  def new
    respond_with(@technology = Technology.new)
  end

  def edit
    new_visit(Technology, params[:id])
    respond_with(@technology = technologies.find(params[:id]))
  end

  def create
    respond_with(@technology = Technology.create(params[:technology]))
  end

  def duplicate
    @technology = technologies.find(params[:id]).duplicate
    redirect_to(edit_technology_path(@technology))
  end

  def update
    @technology = Technology.find(params[:id])
    case params[:do]
      when "preprocess_input_output"
        @technology.preprocess_input_output(@current_sce.id)
      when "update"
        if @technology.update_attributes(params[:technology])
          flash[:notice] = "Technology was successfully updated. #{undo_link(@technology)}"
          redirect_to(edit_technology_path(@technology))
        else
          render :action => "edit"
        end
        return
      when "delete_pv"
        ids = @technology.parameter_values.map(&:id).select { |i| params["cb#{i}"] }
        ParameterValue.where(:id=>ids).map(&:destroy)
      when "combustion_flo"
        in_flow_ids = @technology.in_flows.map(&:id).select { |i| params["f#{i}"] }
        in_flow_ids << @technology.in_flows.first.id
        out_flow_ids = @technology.out_flows.map(&:id).select { |i| params["f#{i}"] }
        out_flow_ids.each do |f|
          in_flow = InFlow.find(in_flow_ids.first)
          out_flow = OutFlow.find(f)
          coef = @technology.combustion_factor(in_flow, out_flow)
          param = Parameter.find_by_name("eff_flo")
          pv = ParameterValue.where("parameter_id=? AND in_flow_id=? AND out_flow_id=?", param, in_flow.id, out_flow.id).first
          if pv
            pv.update_attributes(value: coef, source: "Combustion coefficients")
          else
            ParameterValue.create!(parameter:  param,
                                   technology: @technology,
                                   in_flow:    in_flow,
                                   out_flow:   out_flow,
                                   value:      coef,
                                   source:     "Combustion coefficients",
                                   energy_system: @current_res,
                                   scenario:   @current_res.base_scenario)
          end
        end
      when "add_pv"
        att = params[:pv]
        att[:flow] = Flow.find(att[:flow].to_i) if att[:flow]
        att[:in_flow] = InFlow.find(att[:in_flow].to_i) if att[:in_flow]
        att[:out_flow] = OutFlow.find(att[:out_flow].to_i) if att[:out_flow]
        att[:parameter] = Parameter.find_by_name(att[:parameter])
        att[:commodity] = @current_res.commodities.find_by_name(att[:commodity]) if att[:commodity]
        att[:technology] = @technology
        pv = ParameterValue.new(att)
        if pv.save
          flash[:notice] = "Parameter value was successfully added. #{undo_link(pv)}"
        else
          flash[:alert]  = pv.errors.full_messages.join(", ")
        end
      when "set_act_flo"
        ids = @technology.flows.map(&:id).select { |i| params["f#{i}"] }
        if ids.size > 0
          flow = Flow.find(ids.first)
          p = Parameter.find_by_name("flow_act")
          pv = ParameterValue.where(parameter_id: p.id).technology(@technology).first
          if pv
            ParameterValue.update(pv.id, flow: flow)
            flash[:notice] = "Flow act was successfully updated. #{undo_link(pv)}}"
          else
            pv = ParameterValue.create(energy_system: @technology.energy_system, parameter: p, technology: @technology, flow: flow, value: 0, scenario: @technology.energy_system.base_scenario)
            if pv.save
              flash[:notice] = "Flow act was successfully set. #{undo_link(pv)}"
            else
              flash[:alert]  = pv.errors.full_messages.join(", ")
            end
          end
        end
      when "delete_flo"
        ids = @technology.flows.map(&:id).select { |i| params["f#{i}"] }
        Flow.find_all_by_id(ids).map(&:destroy)
    end if params[:do]
    redirect_to(edit_technology_path(@technology))
  end

  def destroy_all
    Technology.where(id: checkbox_ids).map(&:destroy)
    redirect_to(technologies_url)
  end

  def destroy
    Technology.find(params[:id]).destroy
    redirect_to(technologies_url)
  end

  def suggest
    text = params[:term]
    res = Technology.order(:name).matching_text(text).limit(10).map(&:name)
    res << "..." if res.size==10
    render json: res.to_json
  end

  private

  def undo_link(object)
    view_context.link_to("(undo)", revert_version_path(object.versions.scoped.last), :method => :post)
  end

  def technologies
    Technology.where(:energy_system_id=>@current_res)
  end

end

app/views/technologies/_flow_desc.haml
%input(type="checkbox" name="f#{f.id}")
- if f.flow_act_of?(t)
  %span.flow_act
    = f.id.to_s + ":"
    = raw commodity_url_list(f)
-else
  %span
    = f.id.to_s + ":"
    = raw commodity_url_list(f)
%a(href="#" onclick="edit_flow('#{flow_path(f)}','#{commodities_path}','Out flow',#{f.id})") edit
%br

app/views/technologies/_flow_editor.haml
:javascript
  $(document).ready(function() {
    $('#filter_commodity').keyup(function () {
      fill_avail_commodities('#{commodities_path}',$('#filter_commodity').val());
    });
  });
%div(id="flow_editor" style="display:none; cursor: default")
  .box
    %h2#flow_editor_title Flow Editor
    .block
    %p
      %table
        %thead
          %tr
            %th
              Available commodities
              %input(id="filter_commodity")
            %th Commodity selected
        %tbody
          %tr
            %td.col50
              %select(multiple="multiple" size="10" id="avail_commodity" class="flow_list")
              %p(style="text-align: center")
                %a(href="#" id="add_commodity")
                  & add >>
            %td.col50
              %select(multiple="multiple" size="10" id="commodity_list" class="flow_list")
              %p(style="text-align: center")
                %a(href="#" id="remove_commodity")
                  & << remove
      = link_to 'Apply', '', :id => "flow_apply", :class => "action"
      = link_to 'Cancel', '' , :id => "flow_editor_cancel", :class => "action"

app/views/technologies/_list.json.erb
{
  "sEcho":<%= params[:sEcho].to_json.html_safe || -1.to_json.html_safe %>,
  "iTotalRecords":<%= Technology.count.to_json.html_safe %>,
  "iTotalDisplayRecords":<%= @total_technologies.to_json.html_safe %>,
  "aaData":<%= @technologies.collect do |c|
           [ check_box_tag("cb#{c.id}"),
             link_to(c.name, technology_path(c)),
             truncate(c.description, :omission => "...", :length => 100)]
                                     end.to_json.html_safe %>
}

app/views/technologies/_shortcuts.html.haml
.box
  %h2 Shortcut
  .block
    %p 
      - unless page == :index
        = link_to 'Browse technologies', technologies_path
        %br
      - unless page == :new
        = link_to 'New technology', new_technology_path
        %br

app/views/technologies/edit.haml
.grid_3

  %div(class="box action")
    %h2 Actions
    %br
    %p= link_to 'Browse all', technologies_path, :class => "action browse"
    %p
      = link_to 'New technology', new_technology_path, :class => "action new"
      = link_to 'Duplicate', duplicate_technology_path, :confirm => 'Are you sure?', :method => :post, :class => "action duplicate"
      = link_to 'Delete', @technology, :confirm => 'Are you sure?', :method => :delete, :class => "action delete"
    %p
      = form_tag(technology_path(@technology), :method => "put") do
        %input(type="hidden" name="do" value="preprocess_input_output")
        = submit_tag "Preprocess Input/Output > Efficiency", :class => "button"

  .box
    %h2 Technology
    .block(id="idcard")
      = render :partial => 'shared/id_card', :locals => {:object => @technology, :categories => Technology::CATEGORIES}
  .box
    %h2 Flows
    .block
      = form_tag(technology_path(@technology), :method => "put") do
        %table
          %thead
            %tr
              %th Inflows
          %tbody
            %tr
              %td
                - @technology.in_flows.each do |f|
                  = render :partial => "flow_desc", :locals => { :f => f, :t => @technology }
          %tfoot
            %tr
              %td
                %a(href="#" onclick="add_flow('#{flows_path}','#{commodities_path}','In flow',#{@technology.id})")
                  + Add inflow
        %table
          %thead
            %tr
              %th Outflows
          %tbody
            %tr
              %td
                - @technology.out_flows.each do |f|
                  = render :partial => "flow_desc", :locals => { :f => f, :t => @technology }
          %tfoot
            %tr
              %td
                %a(href="#" onclick="add_flow('#{flows_path}','#{commodities_path}','Out flow',#{@technology.id})")
                  + Add outflow
        %p
          %select(name="do")
            %option(value="set_act_flo") Set activity flow
            %option(value="combustion_flo") Set combustion coeff(s)
            %option(value="delete_flo") Delete checked flow(s)
          = submit_tag "OK"

.grid_9
  .box
    %h2 Input/Output
    .block
      :erb
        <%= render :partial => 'shared/parameter_table',
          :locals => {:object => @technology,
          :pid => "in_out",
          :length_change => "false",
          :filter => "false",
          :request_path => technology_path(@technology),
          :parameters => %w{input output},
          :cols => %w{parameter in_flow out_flow commodity value source},
          :editable => %w{value source},
          :rules => nil } %>

  .box
    %h2 Efficiencies
    .block
      :erb
        <%= render :partial => 'shared/parameter_table',
          :locals => {:object => @technology,
          :pid => "eff_flo",
          :length_change => "false",
          :filter => "false",
          :request_path => technology_path(@technology),
          :parameters => %w{eff_flo },
          :cols => %w{in_flow out_flow value source},
          :editable => %w{value source},
          :rules => nil } %>
  .box
    %h2 Flow parameters
    .block
      :erb
        <%= render :partial => 'shared/parameter_table',
          :locals => {:object => @technology,
          :pid => "flo",
          :length_change => "false",
          :filter => "false",
          :request_path => technology_path(@technology),
          :parameters => %w{flo_bnd_lo flo_bnd_fx flo_bnd_up} +
            %w{flo_share_lo flo_share_fx flo_share_up} +
            %w{peak_prod cost_delivery act_flo},
          :cols => %w{parameter flow commodity time_slice year value source},
          :editable => %w{value source},
          :rules =>  {">flo_bnd" => %w{commodity},
            ">flo_share" => %w{time_slice year},
            "=peak_prod" => %w{flow year},
            "=cost_delivery" => %w{flow},
            "=act_flo" => %w{flow time_slice year}}} %>
  .box
    %h2 Fixed capacities
    .block
      :erb
        <%= render :partial => 'shared/parameter_table',
          :locals => {:object => @technology,
          :pid => "cap",
          :length_change => "false",
          :filter => "false",
          :request_path => technology_path(@technology),
          :parameters => %w{fixed_cap},
          :cols => %w{year value source},
          :editable => %w{value source},
          :rules =>  nil } %>
  .box
    %h2 General
    .block
      :erb
        <%= render :partial => 'shared/parameter_table',
          :locals => {:object => @technology,
          :pid => "gen",
          :length_change => "false",
          :filter => "false",
          :request_path => technology_path(@technology),
          :parameters => %w{life avail cap_act  avail_factor},
          :cols => %w{parameter  time_slice year value source},
          :editable => %w{value source},
          :rules =>  {"=life" => %w{time_slice year},
            "=avail" => %w{time_slice year},
            "=cap_act" => %w{time_slice year} }} %>
  .box
    %h2 Costs
    .block
      :erb
        <%= render :partial => 'shared/parameter_table',
          :locals => {:object => @technology,
          :pid => "cos",
          :length_change => "false",
          :filter => "false",
          :request_path => technology_path(@technology),
          :parameters => %w{cost_vom cost_fom cost_icap},
          :cols => %w{parameter year value source},
          :editable => %w{value source},
          :rules => nil } %>
  .box
    %h2 Bounds
    .block
      :erb
        <%= render :partial => 'shared/parameter_table',
          :locals => {:object => @technology,
          :pid => "bnd",
          :length_change => "false",
          :filter => "false",
          :request_path => technology_path(@technology),
          :parameters =>  %w{act_bnd_lo act_bnd_fx act_bnd_up} +
            %w{cap_bnd_lo cap_bnd_fx cap_bnd_up} +
            %w{icap_bnd_lo icap_bnd_fx icap_bnd_up},
          :cols => %w{parameter time_slice year value source},
          :editable => %w{value source},
          :rules =>  {">cap_bnd" => %w{ time_slice},
            ">icap_bnd" => %w{ time_slice} }} %>

.clear

=render :partial => 'flow_editor'

app/views/technologies/index.haml
:javascript
  $(document).ready(function() {
  	$('.list_table').dataTable( {
  		"bProcessing"    : true,
  		"bServerSide"    : true,
  	    "bFilter"        : true,
        "bLengthChange"  : true,
        "bStateSave"     : true,
        "bSort"          : true,
        "bInfo"          : true,
        "aaSorting"      : [[1,'asc']],
        "sPaginationType": "full_numbers",
        "iDisplayLength" : 25,
        "bAutoWidth"     : false,
  		"sAjaxSource"    : #{list_technologies_path.to_json},
  	    "fnServerData"   : function ( sSource, aoData, fnCallback ) {
            aoData.push( { "name": "set", "value": #{params[:set].to_json} } );
            $.getJSON( sSource, aoData, function (json) {
              fnCallback(json)
            } );
          },
        "aoColumnDefs"   : [ {"bSortable" : false,   "aTargets": [0] } ],
  	    "oLanguage"      : {"sSearch": "Filter:","sProcessing": #{image_tag("spinner.gif").to_json}},
  	    "sDom"           : 'lrft<"dataTable_delete">pi'
  	} );
    $("div.dataTable_delete").html(#{submit_tag('Delete',:class=>'button delete',:confirm => "Are you sure?" ).to_json});
  } );

.grid_2

  .box
    %h2 Action
    .block
      %p= link_to('New technology', new_technology_path, :class => 'action new')

  .box
    %h2 Type
    .block
      %ul.menu
        %li
          - c0 = "active" unless params[:set]
          = link_to "All", technologies_path, :class => c0
          - [["Demand devices", "DMD"], ["Fuel technologies","FUELTECH"]].each do |tag|
            - c = "active" if tag[1]==params[:set]
            %li= link_to tag[0], {:controller => "technologies", :set => tag[1]}, :class => c

  - if @last_visited.size > 0
    .box
      %h2 Last visited
      .block
        %p
          - @last_visited.each do |item|
            = link_to (h item.name), technology_path(item)
            %br

.grid_10
  .box
    %h2 Browse technologies
    %p
      = form_tag(destroy_all_technologies_path,:method => "delete") do
        %table(class="list_table" summary="Technology list")
          %thead
            %th(class='check')
              = check_box_tag("click_check",nil,nil,:class=>"check_all")
            %th(class='name') Name
            %th Description
          %tbody
            %tr
              %td(colspan="3" class="list_table_empty")
                Loading data
    %br
    %br

.clear

app/views/technologies/new.haml
.grid_2
  %div(class="box action")
    %h2 Actions
    %br
    %p= link_to 'Browse all', technologies_path, :class => "action browse"

.grid_10
  .box
    %h2 New Technology
    .block
      = simple_form_for @technology do |f|
        = f.input :name
        = f.input :set_list, :collection => [["Standard Process","P"],["Demand devices","P,DMD"]], :prompt => "Select technology type...", :label=>"Type"
        = f.button :submit, :class => "aligned"
        = f.hidden_field :description, :value => ""
        = f.hidden_field :energy_system_id, value: @current_res.id
.clear