config/routes.rb
Leaqweb::Application.routes.draw do

  get "parameter/suggest"

  devise_for :users

  resources :commodities do
    member do
      post :duplicate
    end
    collection do
      get :list
      delete :destroy_all
      get :suggest
      get :suggest_pollutant
      get :suggest_fuel
    end
  end

  resources :technologies do
    member do
      post :duplicate
      post :emission
    end
    collection do
      get :list
      delete :destroy_all
      get :suggest
    end
  end

  resources :demand_drivers do
    collection do
      get :list
      delete :destroy_all
    end
  end

  resources :demand_driver_values do
    collection do
      put :update_value
    end
  end

  resources :technology_sets do
    collection do
      get :list
      delete :destroy_all
      get :suggest
    end
  end

  resources :commodity_sets do
    collection do
      get :list
      delete :destroy_all
      get :suggest
    end
  end

  resources :combustions do
    collection do
      get :list
      get :import
      get :download
      post :zip
      post :upload
      delete :destroy_all
      put :update_value
    end
  end

  resources :solver_jobs do
    collection do
      get :list
      delete :destroy_all
    end
  end

  resources :parameter_values do
    collection do
      put :update_value
      post :destroy_all
      post :list
    end
  end

  resources :parameters do
    collection do
      get :suggest
    end
  end

  resources :result_sets do
     member do
       get :file
     end
     collection do
       post :import
       get :list
       get :suggest
       delete :destroy_all
     end
  end

  resources :scenarios do
     member do
       get :duplicate
     end
     collection do
       post :select
       get :list
       get :suggest
       delete :destroy_all
     end
  end

  resources :stored_queries do
     member do
       get :duplicate
     end
     collection do
       get :list
       get :import
       get :download
       post :upload
       post :zip
       delete :destroy_all
     end
  end

  resources :versions do
     collection do
       get :list
     end
  end

  resources :flows

  resources :energy_systems do
    member do
      get :backup
      get :restore
      post :upload
    end
    collection do
      post :select
    end
  end

  match '/check_db'          => 'dashboard#check_db', :as => 'check_db'
  match '/reset'             => 'dashboard#reset',    :as => 'reset_db'
  match 'query'              => 'query#index',        :as => 'query'
  get   'query_plot'         => 'query#result_plot',  :as => 'query_plot', :defaults => { :format => 'png' }
  post "versions/:id/revert" => "versions#revert",    :as => "revert_version"

  root :to => 'dashboard#index'

end

app/models/parameter_value.rb
#--
# Copyright (c) 2009-2012, Public Research Center Henri Tudor
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NON INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#++

class ParameterValue < ActiveRecord::Base

  has_paper_trail

  #Relations
  belongs_to :energy_system
  belongs_to :parameter
  belongs_to :technology
  belongs_to :commodity
  belongs_to :commodity_set
  belongs_to :flow
  belongs_to :out_flow
  belongs_to :in_flow
  belongs_to :technology_set
  belongs_to :technology_subset, class_name: "TechnologySet"
  belongs_to :scenario

  #Validations
  validates :energy_system, presence: true
  validates :parameter, presence: true
  validates :time_slice, allow_nil: true, inclusion: {in: %w(AN IN ID SN SD WN WD)}
  validates :scenario, presence: true
  validates_numericality_of :year, allow_nil: true, :greater_than_or_equal_to => 0, :only_integer => true
  validates :value, presence: true, numericality: true

  scope :of, lambda { |names| joins(:parameter).where("parameters.name"=>names).order("parameters.name") }
  scope :technology, lambda { |tech| where(technology_id: tech) }

end

app/controllers/parameter_values_controller.rb
#--
# Copyright (c) 2009-2012, Public Research Center Henri Tudor
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NON INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#++

class ParameterValuesController < ApplicationController

  before_filter :authenticate_user!
  before_filter :check_res!

  respond_to :html, only: [:index]
  respond_to :json, only: [:update_pv,:destroy_all,:create]

  def index
  end

  def create

    params[:pv].keys.each{|k| params[:pv][k] = params[:pv][k].strip }
    params[:pv][:parameter] = Parameter.find_by_name(params[:pv][:parameter])

    params[:pv][:year] = nil unless params[:pv][:year] && params[:pv][:year].size > 0
    params[:pv][:time_slice] = nil unless params[:pv][:time_slice] && Etem::TIME_SLICES.include?(params[:pv][:time_slice])

    params[:pv][:commodity] = @current_res.commodities.find_by_name(params[:pv][:commodity])

    params[:pv][:flow]     = Flow.find_by_id(params[:pv][:flow])
    params[:pv][:in_flow]  = InFlow.find_by_id(params[:pv][:in_flow])
    params[:pv][:out_flow] = OutFlow.find_by_id(params[:pv][:out_flow])

    params[:pv][:commodity_set] = @current_res.commodity_sets.find_by_name(params[:pv][:commodity_set])

    params[:pv][:technology_set] = @current_res.technology_sets.find_by_name(params[:pv][:technology_set])
    params[:pv][:technology_subset] = @current_res.technology_sets.find_by_name(params[:pv][:technology_subset])

    ParameterValue.create(params[:pv])

    render :json => "ok"
  end

  def destroy_all
    ParameterValue.where(id: checkbox_ids).map(&:destroy)
    render json: "ok"
  end

  def list
    columns = [nil,"parameters.name","year","time_slice","technologies.name","commodities.name",
               nil,nil,nil,"commodity_sets.name","technology_sets.name",nil,"value","source",
               "scenarios.name"]
    order        = params[:iSortCol_0] ? columns[params[:iSortCol_0].to_i] : nil
    parameter_values = ParameterValue.includes(:parameter).where("parameters.type"=>nil)
    @totalpv = parameter_values.count # Exclude demand_drivers
    parameter_values = parameter_values.includes(:technology)
    parameter_values = parameter_values.includes(:commodity)
    parameter_values = parameter_values.includes(:commodity_set)
    parameter_values = parameter_values.includes(:scenario)
    columns.each_index do |i|
      if columns[i] && params["sSearch_#{i}"] && params["sSearch_#{i}"].size > 1
        parameter_values = parameter_values.where(["#{columns[i]} LIKE ?","%"+params["sSearch_#{i}"]+"%"])
      end
    end
    current_page = (params[:iDisplayStart].to_i/params[:iDisplayLength].to_i rescue 0) + 1
    info = {page: current_page, per_page: params[:iDisplayLength]}
    info[:order] = "#{order} #{params[:sSortDir_0] || "DESC"}" if order
    @total = parameter_values.count
    if (current_page - 1 ) * params[:iDisplayLength].to_i > @total
        info[:page] = (total/params[:iDisplayLength].to_i rescue 0) + 1
      end
    @displayed = parameter_values.paginate(info)
    render layout: false, :formats => [:json], partial: "parameter_values"
  end

  def update_value
    f = params[:field].split("-")
    value = ParameterValue.update( f.first.to_i, f.last => params[:value]) ? params[:value] : ""
    render json: value
  end

end

app/views/parameter_values/_parameter_values.json.erb
{
    "sEcho":<%= params[:sEcho].to_json.html_safe || -1.to_json.html_safe %>,
    "iTotalRecords":<%= @totalpv.to_json.html_safe %>,
    "iTotalDisplayRecords":<%= @total.to_json.html_safe %>,
    "aaData":<%= @displayed.collect do |c|
                   [ check_box_tag("cb#{c.id}"),
                     c.parameter.name,
                     c.year,
                     c.time_slice,
                     c.technology ?  c.technology.name : "",
                     c.commodity ?  c.commodity.name : "",
                     short_flow(c.flow),
                     short_flow(c.in_flow),
                     short_flow(c.out_flow),
                     c.commodity_set ?  c.commodity_set.name : "",
                     c.technology_set  ?  c.technology_set.name : "",
                     c.technology_subset  ?  c.technology_subset.name : "",
                     "<span id='#{c.id}-value' class='edit'>#{c.value}</span>",
                     "<span id='#{c.id}-source' class='edit'>#{c.source}</span>",
                     c.scenario ?  c.scenario.name : ""
                   ]
                 end.to_json.html_safe %>
}

app/views/parameter_values/index.haml
:javascript
  var pvtable;
  var currentcol = null;
  function draw_editable() {
    $('.edit').editable(#{raw update_value_parameter_values_path.to_json},{
        style   : 'inherit',
        width   : "100%",
        height  : 15,
        method  : "PUT",
        id      : 'field',
        submitdata: {
          authenticity_token: #{raw form_authenticity_token.to_json}
        }
    });
  }
  function delete_all() {
    if (confirm("Are you sure you want to delete")) {
      var mydata = new Object();
      $('input:checkbox:checked').each(function() {
        mydata[$(this).attr('id')]=$(this).val();
      });
      $.ajax({
        'url': #{destroy_all_parameter_values_path.to_json},
        'type': 'POST',
        'data': mydata,
        'async': false,
        'dataType': 'json'
      });
      pvtable.fnDraw();
    }
  }
  function add_pv() {
    var mydata = new Object();
    var attributes = new Object();
    var fields = ['parameter','year','time_slice','commodity','flow','in_flow','out_flow',
                  'commodity_set','technology_set','technology_subset','value','source','scenario']
    fields.forEach(function (element) {
      if ($('#new_'+element)) {
        console.log(element + ': ' + $('#new_'+element).val());
        attributes[element] = $('#new_'+element).val();
      }
    });
    mydata['pv'] = attributes;
    $.ajax({
      'url': #{parameter_values_path.to_json},
      'type': 'POST',
      'data': mydata,
      'async': false,
      'dataType': 'json'
    });
    pvtable.fnDraw();
  }
  var typewatch = (function(){
    var timer = 0;
    return function(callback, ms){
      clearTimeout (timer);
      timer = setTimeout(callback, ms);
    }
  })();
  function ShowHide(iCol,iCol2){
    var bVis = pvtable.fnSettings().aoColumns[iCol2].bVisible;
    pvtable.fnSetColumnVis( iCol2, bVis ? false : true );
    $("a#switch"+iCol).toggleClass('colVisible');
  }
  $(document).ready(function() {
  	pvtable = $('#parameter_value_table').dataTable( {
  		"bProcessing"    : true,
  		"bServerSide"    : true,
  	    "bFilter"        : true,
        "bLengthChange"  : true,
        "bStateSave"     : true,
        "bSort"          : true,
        "bInfo"          : true,
        "aaSorting"      : [[1,'asc']],
        "sPaginationType": "full_numbers",
        "iDisplayLength" : 10,
        "bAutoWidth"     : false,
  		"sAjaxSource"    : #{list_parameter_values_path.to_json},
  	    "fnServerData"   : function ( sSource, aoData, fnCallback ) {
            $.ajax( {
              "dataType": 'json',
              "type":     "POST",
              "url": sSource,
              "data": aoData,
              "success": fnCallback
            } );
          },
        "fnDrawCallback": function() { draw_editable(); },
        "aoColumnDefs"   : [ {"bSortable" : false,   "aTargets": [0,6,7,8] } ],
  	    "oLanguage"      : {"sSearch": "Filter:","sProcessing": #{image_tag("spinner.gif").to_json}},
  	    "sDom"           : 'lrit<"dataTable_delete">p<"dataTable_add">'
  	} );
    $("div.dataTable_delete").html(#{link_to_function('Delete checked','delete_all()',:class=>'action delete').to_json});
    $("div.dataTable_add").html(#{link_to_function('Add','add_pv()',:class=>'action add_pv').to_json});
    $( ".suggest_commodity" ).autocomplete({
      source: #{suggest_commodities_path.to_json},
      minLength: 2
    });
    $( ".suggest_technology" ).autocomplete({
      source: #{suggest_technologies_path.to_json},
      minLength: 2
    });
    $( ".suggest_parameter" ).autocomplete({
      source: #{suggest_parameters_path.to_json},
      minLength: 2
    });
    $( ".suggest_commodity_set" ).autocomplete({
      source: #{suggest_commodity_sets_path.to_json},
      minLength: 2
    });
    $( ".suggest_technology_set" ).autocomplete({
      source: #{suggest_technology_sets_path.to_json},
      minLength: 2
    });
    $( ".suggest_scenario" ).autocomplete({
      source: #{suggest_scenarios_path.to_json},
      minLength: 2
    });
    for(var i in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]){
      $("thead input#col"+i).keyup( function () {
        currentcol = this.id.substr(3,2);
        typewatch(function () {
          pvtable.fnFilter($("thead input#col"+currentcol).val(),currentcol);
        }, 500);
      });
      if (pvtable.dataTableSettings[0].oLoadedState.aaSearchCols[i]){
        $("thead input#col"+i).val(pvtable.dataTableSettings[0].oLoadedState.aaSearchCols[i][0]);
      }
      if (pvtable.fnSettings().aoColumns[i].bVisible) {
        $("a#switch"+i).addClass('colVisible')
      }
    }
  });
.grid_12
  .box
    %h2 Browse Parameter Values
    %p
      %br
      Show/hide columns
      |
      - cols = %w{Parameter Year TS Technology Commodity Flow InFlow OutFlow CommoditySet TechnologySet SubTechnologySet Value Source Scenario}
      - cols.each_with_index do |col,i|
        = link_to_function col, "ShowHide(#{i},#{i+1})", :id => "switch#{i}"
        |
    = form_tag(destroy_all_parameter_values_path) do
      %table(id="parameter_value_table" summary="Parameter Values list")
        %thead
          %tr
            %th(class='check')
            %th Parameter
            %th Year
            %th TS
            %th Technology
            %th Commodity
            %th Flow
            %th InFlow
            %th OutFlow
            %th CommoditySet
            %th TechnologySet
            %th SubTechnologySet
            %th Value
            %th Source
            %th Scenario
          %tr
            %th(class='check inputs')
              = check_box_tag("click_check",nil,nil,:class=>"check_all")
            %th(class='inputs')
              %input(class="textcell" id="col1")
            %th(class='inputs')
              %input(class="textcell" id="col2" size="4")
            %th(class='inputs')
              %select(id="col3" class="tiny")
                = options_for_select([""] + %w{AN SD SN ID IN WN WD})
            %th(class='inputs')
              %input(class="textcell" id="col4")
            %th(class='inputs')
              %input(class="textcell" id="col5")
            %th(class='inputs')
            %th(class='inputs')
            %th(class='inputs')
            %th(class='inputs')
              %input(class="textcell" id="col9")
            %th(class='inputs')
              %input(class="textcell" id="col10")
            %th(class='inputs')
              %input(class="textcell" id="col11")
            %th(class='inputs')
              %input(class="textcell" id="col12")
            %th(class='inputs')
              %input(class="textcell" id="col13")
            %th(class='inputs')
              %input(class="textcell" id="col14")
        %tbody
          %tr
            %td(colspan="15" class="list_table_empty")
              Loading data
        %tfoot
          %tr
            %th(class="check inputs")
            %th(class='inputs')
              %input(class="textcell suggest_parameter" id="new_parameter" name="pv[parameter]")
            %th(class='inputs')
              %input(class="textcell" id="new_year" name="pv[new_year]")
            %th(class='inputs')
              %select(id="new_time_slice" class="tiny")
                = options_for_select([""] + %w{AN SD SN ID IN WN WD})
            %th(class='inputs')
              %input(class="textcell suggest_technology" id="new_technology" name="pv[technology]")
            %th(class='inputs')
              %input(class="textcell suggest_commodity" id="new_commodity" name="pv[commodity]")
            %th(class='inputs')
              %input(class="textcell" id="new_flow" name="pv[flow]")
            %th(class='inputs')
              %input(class="textcell" id="new_in_flow" name="pv[in_flow]")
            %th(class='inputs')
              %input(class="textcell" id="new_out_flow" name="pv[out_flow]")
            %th(class='inputs')
              %input(class="textcell suggest_commodity_set" id="new_commodity_set" name="pv[commodity_set]")
            %th(class='inputs')
              %input(class="textcell suggest_technology_set" id="new_technology_set" name="pv[technology_set]")
            %th(class='inputs')
              %input(class="textcell suggest_technology_set" id="new_technology_subset" name="pv[technology_subset]")
            %th(class='inputs')
              %input(class="textcell" id="new_value" name="pv[value]")
            %th(class='inputs')
              %input(class="textcell" id="new_source" name="pv[source]")
            %th(class='inputs')
              %input(class="textcell suggest_scenario" id="new_scenario" name="pv[scenario]")
      %br
      %br
      %br
.clear